### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by gauntl3t12** [woelper/dircpy#7]
Running with v0.3.15, I'm getting an infinite loop. I was attempting to copy all files in my current directory to a sub directory only when files have a specific ending.

**Comment by woelper** [comment]
Thank you so much for reporting. Would you be able to describe the steps to reproduce it, and possibly even provide a zip file containing a file structure that causes this if you think that helps?

**Comment by woelper** [comment]
Was able to reproduce it - working on a fix.

**Comment by woelper** [comment]
This should be fixed now in 7c51fa6. Could you please check once released that this fixes your issue?

**Comment by gauntl3t12** [comment]
Yup, will do. Thanks for the quick turn around!

**Comment by gauntl3t12** [comment]
It works great!
