### ISSUE TITLE
include_filters not working

### ISSUE THREAD

**Issue by giovannimirarchi420** [woelper/dircpy#8]
Hi,

I'm using your crate, which perfectly meets my needs and works very well. However, I've encountered an issue with the `include_filters` option when using both the `CopyBuilder` and `copy_dir_advanced` methods.

Here's my code:

```rust
    fn folder_backup(settings: BackupConfig) -> anyhow::Result<()> {
        let destination_path = PathBuf::from(&settings.backup_destination).join("emergency-backup");
        info!(target: "general", "{:?}", settings.extension_type.iter().map(|ext| ".".to_owned() + ext.as_str()).collect::<Vec<_>>());
        match copy_dir_advanced(&settings.backup_source,
                                destination_path, false, true,
                                true, vec!(),
                                if settings.extension_only { settings.extension_type.iter().map(|ext| ".".to_owned() + ext.as_str()).collect() } else { vec!() } ) {
            Ok(_) => { Ok(()) }
            Err(err) => { error!("{}", err.to_string()); bail!(FileTransferError) }
        }
    }
```

The printed line before the `copy_dir_advanced` call shows:
`2024-07-12 12:57:39 | INFO  | path/to/file.rs:203 — [".pdf", ".txt"]`

I initially tried using the `extension_type` vector directly (in "ext" format, without the leading dot). However, I saw an example in the documentation that used the dot before the extension, so I tried that as well, but it still doesn't work.
```rust
   let destination_path = PathBuf::from(&settings.backup_destination).join("emergency-backup");
        info!(target: "general", "{:?}", settings.extension_type.iter().map(|ext| ".".to_owned() + ext.as_str()).collect::<Vec<_>>());
        let mut builder = CopyBuilder::new(&settings.backup_source, destination_path);
        if settings.extension_only {
            for ext in settings.extension_type {
                builder = builder.with_include_filter(ext.as_str());
            }
        }
        match builder.run() {
            Ok(_) => { Ok(()) }
            Err(err) => { error!("{}", err.to_string()); bail!(FileTransferError) }
        }
```
Am I missing something?

Thank you in advance.

**UPDATE**

Running this code seems not working as well:

```rust
        let mut builder = CopyBuilder::new(&settings.backup_source, destination_path)
            .with_include_filter(".txt")
            .with_include_filter(".pdf").run();
```

**Comment by woelper** [comment]
Really well spotted, and thank you so much for raising this issue!

Also please accept my apologies for the late reply. I've left one suggestion on the PR to use an iterator instead, please let me know what you think!

**Comment by giovannimirarchi420** [comment]
@woelper thanks for your reply.
But honestly, I can't find your comment, am I wrong?

**Comment by woelper** [comment]
I don't think you are wrong. Can you see it here?
https://github.com/woelper/dircpy/pull/9#pullrequestreview-2191880258

**Comment by woelper** [comment]
Thank you again - I just published a release with your fixes.

**Comment by giovannimirarchi420** [comment]
Hi @woelper,
Have you had a chance to test the changes? I'm encountering issues and I'm not sure if I'm doing something incorrectly. When I execute the run() method without applying any filters, no data is copied, only the folder structure.
It's the same for you?

**Comment by AdamLeyshon** [comment]
I have the same problem, no files are copied now, just the folder structure.

```rust
if !self
  .include_filters
  .iter()
  .any(|f| entry.path().to_string_lossy().contains(f))
  {
    continue 'files;
  }
```

should probably check `self.include_filters.is_empty()` before doing the filter since if the list is empty `any()` will always be false, which here is inverted and the branch is always taken

Please see https://github.com/woelper/dircpy/pull/10

**Comment by woelper** [comment]
Yes, I think you are right. Many thanks for the fix, which I will look at in a second. I will also add a test to make sure an empty filter should copy.

In the long term it might make sense to move the filtering to the beginning of the loop of walkdir  so only files matching the filter are processed if the filter exists.

**Comment by woelper** [comment]
I made a release on crates.io with the fixes and wrote a test. Thanks again!
